// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nivmsvipacxkopebmxpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pdm1zdmlwYWN4a29wZWJteHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjE2MTUsImV4cCI6MjA3MTg5NzYxNX0.6G3jg_x3PLpTxtLm7muYEPw91wL4LJwug0VU0Uzdc_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});